In [1]:
import numpy as np

In [4]:
arr1 = np.array([5,6,9])
print("Number of dimension = ",arr1.ndim)
arr2 = np.array([[5,6,9],[5,6,9],[5,6,9]])
print("Number of dimension = ",arr2.ndim)

Number of dimension =  1
Number of dimension =  2


In [8]:
print(arr1.itemsize)
print(arr2.itemsize)
print(arr1.dtype)
print(arr2.dtype)

8
8
int64
int64


In [15]:
float_arr = np.array([[5,6,9],[5,6,9],[5,6,9]],dtype=np.float64)
print(float_arr)
print(float_arr.itemsize)
print(float_arr.dtype)
print(float_arr.size)
print(float_arr.shape)

complex_array = np.array([[5,6,9],[5,6,9],[5,6,9]],dtype=complex)
print(complex_array)


[[5. 6. 9.]
 [5. 6. 9.]
 [5. 6. 9.]]
8
float64
9
(3, 3)
[[5.+0.j 6.+0.j 9.+0.j]
 [5.+0.j 6.+0.j 9.+0.j]
 [5.+0.j 6.+0.j 9.+0.j]]


In [16]:
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
ones_array = np.ones((4,6))
print(ones_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [18]:
list = range(5)
print(list)

range(0, 5)


In [20]:
range_array = np.arange(1,8,2)
print(range_array)

[1 3 5 7]


In [21]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [22]:
np.linspace(1,5,100).dtype

dtype('float64')

In [27]:
a = np.array([1,2,3,4,5])
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
# to flatten the array
a.ravel()

array([1, 2, 3, 4, 5])

In [30]:
a.min()

1

In [31]:
a.max()

5

In [32]:
a.sum()

15

In [38]:
a.sum(axis=0)
# a.sum(axis=1)
np.sqrt(a)
np.std(a)

1.4142135623730951

In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[1,2]])
x + y
x*y
x.dot(y)
x

array([[1, 2],
       [3, 4]])